version: '3.6'

volumes:
  data:

services:
  db:
    image: mongo:3.2
    restart: always
    entrypoint: mongod --smallfiles
    volumes:
      - data:/data/db

  rocketchat:
    image: rocket.chat:latest
    restart: always
    environment:
      ROOT_URL: 'http://localhost'
    ports:
      - "3000:3000"
